### ISSUE TITLE
CopyText component causing Warning messages in console

### ISSUE THREAD

**Issue by StrungSafe** [CashScript/cashscript-playground#13]
Testing w/ Firefox I see console warning messages

```validateDOMNesting(...): <p> cannot appear as a descendant of <p>.```
and
```validateDOMNesting(...): <div> cannot appear as a descendant of <p>```

these were introduced by cd21e48f1fb2bb1160236d36c9285cc03b697bdd

**Comment by StrungSafe** [comment]
I don't mind fixing this since I introduced it

**Comment by StrungSafe** [comment]
Verified that one was existing and one I created; still happy to resolve both though

**Comment by rkalis** [comment]
Oh thanks for catching that and happy to hear that you want to resolve them as well!

**Comment by StrungSafe** [comment]
@rkalis @mr-zwets posted a PR (I can't assign) when you have a chance please review/merge

would implementing a CODEOWNERS file be acceptable for this repository? my understanding that'll auto add the users/teams defined
