### ISSUE TITLE
Improve Support of Negative Int Arguments

### ISSUE THREAD

**Issue by StrungSafe** [CashScript/cashscript-playground#26]
Int is a signed type and should be able to support negative numbers.

When trying to provide a negative number as a constructor argument or function argument a popup dialog is shown with "Should only have numbers in the integer field". 
![image](https://github.com/CashScript/cashscript-playground/assets/10366241/421a538d-0e46-480c-a671-722dd26ca239)

This is slightly confusing as it's not clear how else to provide a negative number

Although the UI gives this warning it does not prevent the user from providing the value as an argument for contract construction or running a contract function.

Could not show the warning when a "-" is entered first or provide an alternative way to denote the value is negative.

**Comment by mr-zwets** [comment]
Thanks for the issue! Just patched this 😄
