### ISSUE TITLE
Add copy buttons to the smart contract addresses

### ISSUE THREAD

**Issue by mr-zwets** [CashScript/cashscript-playground#6]
Add copy buttons to the smart contract addresses for convenience

**Comment by StrungSafe** [comment]
For this issue do you want an icon (like a clipboard icon) the user clicks or is clicking the header and/or the address itself enough to initiate the copy?

I'm also thinking the token address should have the same functionality?

**Comment by mr-zwets** [comment]
Hi! Thanks for bringing this back up!
I've found myself copy pasting a whole lot while using the playground in the past 👍 

> For this issue do you want an icon (like a clipboard icon) the user clicks or is clicking the header and/or the address itself enough to initiate the copy?

I think a simple 'click to copy' on the text items could work if you add a style to make the mouse into a cursor.

>  I'm also thinking the token address should have the same functionality?

Yeah for the smart contract, would add it both the normal & token address.
Might also want it for the different text items for each wallet in the Wallets section. (having copy icons all over the screen is also not great)

Ideally we'd have a small alert at the bottom of the screen when something is copied to clipboard, but I'm not sure bootstrap has anything specific for this.

**Comment by StrungSafe** [comment]
using bootstrap I can easily get a notification like this (CSS isn't my strongest strength)

![image](https://github.com/CashScript/cashscript-playground/assets/10366241/451a3ad3-c90e-4d69-ba23-4b5b9d220c71)

This would popup and then timeout after 1 sec (or any other arbitrary length you want)

**Comment by rkalis** [comment]
This was implemented by @StrungSafe in #12. Thank you for the contribution!
